### ISSUE TITLE
Cloud Discovery onboarding out of date

### ISSUE THREAD

**Issue by zwaqar-git** [PaloAltoNetworks/prisma-cloud-docs#318]
## Documentation link

The issue is that the Cloud Discovery documentation is completely out of date and does not include how to onboard with the Manage > Cloud Accounts feature which is new to Compute. This has been needing to be updated for months now and I am surprised we still have not addressed this as I have SEVERAL customers complaining about this. 

Huge inaccuracy with Cloud Discovery

## Suggested fix
Update documentation for Cloud Discovery with new method of onboarding Cloud Accounts into Compute.

**Comment by Pubs-MV** [comment]
https://github.com/PaloAltoNetworks/prisma-cloud-docs/issues/338
