### ISSUE TITLE
Azure Function Supports .NET 3.1 and 6.0

### ISSUE THREAD

**Issue by zwaqar-git** [PaloAltoNetworks/prisma-cloud-docs#413]
Current documentation states Azure functions support only .NET 3.1. "Prisma Cloud supports .NET Core 3.1 on Windows." However, in the release notes for 22.06, it mentions Azure Functions supports .NET 3.1 and 6.0. We have tested and found that we do support both 3.1 and 6.0, but customers are confused because documentation says otherwise. Can we please update the documentation page to reflect this?

**Comment by Pubs-MV** [comment]
Yes, @zwaqar-git 

Clarification in https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/383
and
https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/410

**Comment by Pubs-MV** [comment]
The docs will be republished 7/22, please open a new issue if  your questions are not addressed. Thankyou!
