### ISSUE TITLE
Document OpenID Connect support for Azure AD

### ISSUE THREAD

**Issue by grevach** [PaloAltoNetworks/prisma-cloud-docs#448]
We currently have an article describing PCC integration with OpenID Connect: https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/authentication/oidc.

The article only describes the steps for PingOne and Okta, and does not refer to the process required in Azure AD, which is also supported with OpenID Connect.

We should extend the article to include the required steps for integrating with Azure AD.

The request also came up in this support case from Morgan Stanley: https://redlock.atlassian.net/browse/PCSUP-10521

**Comment by Tomerit** [comment]
HI, 
Below are general steps required for the integration with Azure AD.

Notes:
* Formalization & tuning are needed.
* I can walkthrough the steps with someone if necessary.

## Integration environment setup
* Register Application:
  * Go to https://portal.azure.com/#home
  * Look for Azure Active Directory service
  * Press on “app registration” then “New registration”:
    * Choose a name, keep the supported account type to Twistlock only - single tenant.
    * Redirect URI:
      * Web platform
      * https://<CONSOLE_URL>:8083/api/v1/authenticate/callback/oidc 
    * Register the app.
* Add a client secret:
  * Go to certificates & secrets.
  * Add a new client secret, keep in mind the secret’s value can only be viewed on creation, should be copied and kept in a safe place for now.
* Optional Claims:
  * Go to Token Configuration.
  * Add a group claim:
    * Select Groups assigned to the application.
  * Add an optional claim (**optional step - SKIP**):
    * Note: This step is optional as the email can also be retrieved by UserInfo endpoint, thus it is not required to add it to the ID token as well.
    * Select ID then email (The user should have one, check the user's profile if email was set or contact admin).
    * API permissions:
      * Go to API permissions.
      * Add a delegate permission using Microsoft Graph.
      * Under OpenId permissions choose email, openid, profile.
* Create new application group:
  * In Azure AD go to Groups.
  * Create a new group, keep defaults.
* Assign the group to the application:
  * In Azure AD go to Enterprise applications.
  * Find and navigate to the application you’ve created earlier.
  * Click on properties and mark Assignment required.
    * Note: it is up for the customer to choose how he had like to manage the application settings. Meaning he can decide that direct assignment is not required -> assigning (not make much sense but possible) OR not assigning any groups or users to the application -> in group claim - "Select Groups assigned to the application" will result in empty groups because none were assigned. Therefore, this property should intuitively be correlated with the group claim.
  * Click on assign users and groups.
  * Press add, select the group you’ve created earlier. 
  * Press add, select your user.

## Edit Console Identity Provider settings
* Navigate to Manage/ Authentication/ Identity Providers/ OpenID Connect:
   * Enabled OpenID Connect
   * Fill the settings fields:
     * Client ID: Application (client) ID from Azure AD
     * Client Secret: The client secret created for the app
   * Issuer URL:  
     * Go to Azure Active Directory -> App registrations (on the left) -> your owned registered app.
     * In Azure AD registered app click on Endpoints, then copy and navigate to OpenID Connect metadata document.
     * Copy the issuer value from the JSON.
       * Note: Usually https://login.microsoftonline.com/<TENANT_ID>/v2.0
   * Group scope: is not required and must be left empty.
   * Group claim: groups
   * User claim (example): preferred_username 
     * Note: This claim can automatically be retrieved as it is under the profile scope, thus is not required to be added as an optional claim.
   * Click save

**Comment by grevach** [comment]
> HI, Below are general steps required for the integration with Azure AD.
> 
> Notes:
> 
> * Formalization & tuning are needed.
> * I can walkthrough the steps with someone if necessary.
> 
> ## Integration environment setup
> * Register Application:
>   
>   * Go to https://portal.azure.com/#home
>   * Look for Azure Active Directory service
>   * Press on “app registration” then “New registration”:
>     
>     * Choose a name, keep the supported account type to Twistlock only - single tenant.
>     * Redirect URI:
>       
>       * Web platform
>       * https://<CONSOLE_URL>:8083/api/v1/authenticate/callback/oidc
>     * Register the app.
> * Add a client secret:
>   
>   * Go to certificates & secrets.
>   * Add a new client secret, keep in mind the secret’s value can only be viewed on creation, should be copied and kept in a safe place for now.
> * Optional Claims:
>   
>   * Go to Token Configuration.
>   * Add a group claim:
>     
>     * Select Groups assigned to the application.
>   * Add an optional claim (**optional step - SKIP**):
>     
>     * Note: This step is optional as the email can also be retrieved by UserInfo endpoint, thus it is not required to add it to the ID token as well.
>     * Select ID then email (The user should have one, check the user's profile if email was set or contact admin).
>     * API permissions:
>       
>       * Go to API permissions.
>       * Add a delegate permission using Microsoft Graph.
>       * Under OpenId permissions choose email, openid, profile.
> * Create new application group:
>   
>   * In Azure AD go to Groups.
>   * Create a new group, keep defaults.
> * Assign the group to the application:
>   
>   * In Azure AD go to Enterprise applications.
>   * Find and navigate to the application you’ve created earlier.
>   * Click on properties and mark Assignment required.
>     
>     * Note: it is up for the customer to choose how he had like to manage the application settings. Meaning he can decide that direct assignment is not required -> assigning (not make much sense but possible) OR not assigning any groups or users to the application -> in group claim - "Select Groups assigned to the application" will result in empty groups because none were assigned. Therefore, this property should intuitively be correlated with the group claim.
>   * Click on assign users and groups.
>   * Press add, select the group you’ve created earlier.
>   * Press add, select your user.
> 
> ## Edit Console Identity Provider settings
> * Navigate to Manage/ Authentication/ Identity Providers/ OpenID Connect:
>   
>   * Enabled OpenID Connect
>   * Fill the settings fields:
>     
>     * Client ID: Application (client) ID from Azure AD
>     * Client Secret: The client secret created for the app
>   * Issuer URL:
>     
>     * Go to Azure Active Directory -> App registrations (on the left) -> your owned registered app.
>     * In Azure AD registered app click on Endpoints, then copy and navigate to OpenID Connect metadata document.
>     * Copy the issuer value from the JSON.
>       
>       * Note: Usually https://login.microsoftonline.com/<TENANT_ID>/v2.0
>   * Group scope: is not required and must be left empty.
>   * Group claim: groups
>   * User claim (example): preferred_username
>     
>     * Note: This claim can automatically be retrieved as it is under the profile scope, thus is not required to be added as an optional claim.
>   * Click save

@rcaballeromx please see the steps described by Tomer

**Comment by rcaballeromx** [comment]
Addressed in [PR 477](https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/477)
