### ISSUE TITLE
Add the audit types to ATTACK explorer techniques mapping to the docs

### ISSUE THREAD

**Issue by grevach** [PaloAltoNetworks/prisma-cloud-docs#457]
In one of the previous releases, we added the ATTACK explorer.
Each of our audits (runtime, admission, etc.) is mapped to single or multiple techniques.

We should add this mapping to the ATTACK explorer article https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/runtime_defense/attack.

The mapping is in this spreadsheet: https://docs.google.com/spreadsheets/d/1aWuAOj3eSwBVTWadw_QGDvZRBgtjOdTXz1Ih6ptHgus/edit#gid=1878487739.

In the spreadsheet:
* **Techniques** - are the techniques that the audit is always mapped to
* **Possible Additional Techniques** - are techniques that the audit can optionally be mapped to, depending on changing information from the audit. For example, for some audits, on new files being created we will check if the process that created the file is a compiler, and if so, we also map the audit to the Compile After Delivery technique.

**Comment by Pubs-MV** [comment]
Hey @grevach can we link to the spreadsheet instead of adding a separate table in the docs?

I did that with some of Paul's spreadsheets for the public sector docs. https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-compute-edition-public-sector/Release_Findings/v22_01_840/console_vulnerabilities

**Comment by grevach** [comment]
Hi @Pubs-MV, I'm not sure this is the right approach since then we need to make sure everyone has access to it, and if someone needs to edit then we'll need to make sure they have edit access. WDYT?

**Comment by Pubs-MV** [comment]
@grevach when you say everyone, do you mean our PMs? Or Eng too? We can add as many collaborators as we need. I can show you how it works on GDrive.

@iansk is there a good way to pull content in from a spreadsheet into adoc directly without manually creating the table/data?

I am trying to find the best way to reduce maintenance overhead.

**Comment by iansk** [comment]
@Pubs-MV I would take this approach:

1. When there's an update to the Google sheet, export it to a CSV file.

2. Commit the updated CSV file to the prisma-cloud-docs repo.

3. In your ADOC source file, set up your table populate itself directly from the CSV file:

```
[%header,format=csv]
|===
include::tracks.csv[]
|===
```

**Comment by grevach** [comment]
> * When there's an update to the Google sheet, export it to a CSV file.
> *

@Pubs-MV @iansk 

It is of course your call on how to implement it in the docs repo, I'm just concerned about the maintenance of the spreadsheet itself and it being outside of the docs repo, in my google drive... this is why I suggested creating the table in the doc.
If you prefer keeping it in a spreadsheet, then I suggest at least creating a copy of it in the PM drive for example, so it won't be missed along the way.

**Comment by iansk** [comment]
@grevach We've changed how we're going to approach this problem. From the doc source, we're going to directly import your Google spreadsheet and insert it into a table in the docs. There will be no separate steps to create a CSV file and check it into the repo; instead, we'll just pull it from over the network at publish-time. That means every time we publish the docs, we'll get the latest data from the spreadsheet, keeping your spreadsheet and our docs fully in sync. This approach should substantially reduce maintenance effort.

Our doc source will look something  like this:

```
|===
include::https://docs.google.com/spreadsheets/d/e/2PAC...wIEY[]
|===
```

**Comment by iansk** [comment]
@grevach Can we put your sheet in the PM drive under a new directory called "Docs"? That way, the single source of truth will always be this sheet, where PMs with edit access can update it as required.

We've got other PM-maintained spreadsheets we'd also want to put in the "PM-drive/Docs" dir. 

WDYT?

**Comment by grevach** [comment]
> @grevach Can we put your sheet in the PM drive under a new directory called "Docs"? That way, the single source of truth will always be this sheet, where PMs with edit access can update it as required.
> 
> We've got other PM-maintained spreadsheets we'd also want to put in the "PM-drive/Docs" dir.
> 
> WDYT?

@iansk sure, do you want me to put it there? or that you are creating a copy?

**Comment by iansk** [comment]
@grevach I just tried to create a "Docs" directory in the PM drive, but I don't have permission. Do you have permission to do it?

**Comment by grevach** [comment]
> @grevach I just tried to create a "Docs" directory in the PM drive, but I don't have permission. Do you have permission to do it?

@iansk I created a "Docs" folder and added the spreadsheet to it

**Comment by iansk** [comment]
@grevach Thanks! :)

One last step: Can you please transfer ownership of the spreadsheet to me?
