### ISSUE TITLE
Cloud Discovery onboarding out of date (still seems to be several product versions behind)

### ISSUE THREAD

**Issue by cmcconnell-mvi** [PaloAltoNetworks/prisma-cloud-docs#481]
## Enterprise PCC SaaS Cloud Disco doc specifies a non-existing location
- per the existing doc:
  _- Review the scan report.
  Go to Monitor > Compliance > Cloud Discovery to see the scan report in tabular format._
However, this is not possible to navigate to, as these don't exist.  Should this instead be Manage > Cloud Accounts... ? but not sure about this either as we can't find Cloud Discovery.   It's possible this is related to us being in Azure and perhaps this works in other cloud providers such as AWS?

#### stale information, request for improvement, inaccuracy

- Suggested fix

  - Update the docs for the latest SaaS console PCC version to show where we can find Cloud Discovery

**Comment by Pubs-MV** [comment]
completed with https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/513
