### ISSUE TITLE
VSCode Docs

### ISSUE THREAD

**Issue by andydkelly-ig** [PaloAltoNetworks/prisma-cloud-docs#524]
## Documentation link

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/get-started/connect-your-repositories/Connect-vscode

## Describe the problem

There seems to be a documentation page for VSCode integration, but there's nothing of value and many of the links take you to generic Admin docs, or to a 404, or in a loop.

## Suggested fix

Remove the page if there isn't actually any VSCode integration. Update the doc page with something useful.

**Comment by Pubs-MV** [comment]
The correct page is https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-code-security/get-started/connect-your-repositories/connect-vscode.

The link was updated to use "c" instead of "C" in "connect-vscode".
