### ISSUE TITLE
Grammer issue in Jenkins Plugin documentation for Prisma Cloud Compute

### ISSUE THREAD

**Issue by oorryy** [PaloAltoNetworks/prisma-cloud-docs#723]
## Documentation link

https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/continuous_integration/jenkins_plugin.adoc

## Describe the problem

1. A**n** developer commits a change, which triggers a build.

## Suggested fix

Should be A developer

**Comment by Pubs-MV** [comment]
fixed.
