### ISSUE TITLE
Problems with Images

### ISSUE THREAD

**Issue by oorryy** [PaloAltoNetworks/prisma-cloud-docs#746]
## Documentation link

- https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/install/getting_started.adoc
- https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/welcome/pcee_vs_pcce.adoc

## Describe the problem
- In the first link (getting started), the image is outdated and includes Twistlock terminology, logo, etc. This needs to be changed to Prisma Cloud. Also note that it says "RASP defender", which should be App-Embedded Defender
- In the second page (PCEE vs PCCE), in the PDF version, the image is bigger than the page width and gets cut.

**Comment by rcaballeromx** [comment]
Thank you for filing the issue. I've addressed it in [PR 830](https://github.com/PaloAltoNetworks/prisma-cloud-docs/pull/830)
