### ISSUE TITLE
CWPP Tag information update

### ISSUE THREAD

**Issue by cmartinsjr** [PaloAltoNetworks/prisma-cloud-docs#753]
## Documentation link
https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/vulnerability_management/scan_reports.adoc

and 

https://github.com/PaloAltoNetworks/prisma-cloud-docs/blob/master/compute/admin_guide/configure/tags.adoc

## Describe the problem
There is a note in the "scan_reports.adoc" that states: 
"For tags that are not used as policy exceptions, all user roles that can view the scan results and have the Collections and Tags permission, are allowed to assign these tags on CVEs. Assigning tags that are used as policy exceptions is allowed only for Admin, Operator, and Vulnerability Manager user roles. Custom roles aren’t allowed to set these tags, regardless of their other permissions."

This information should really be included in the "tags.adoc" document, as this is directly relevant to anyone that visits the tag documentation and belongs there.

## Suggested fix
add this note to "tags.adoc":
"For tags that are not used as policy exceptions, all user roles that can view the scan results and have the Collections and Tags permission, are allowed to assign these tags on CVEs. Assigning tags that are used as policy exceptions is allowed only for Admin, Operator, and Vulnerability Manager user roles. Custom roles aren’t allowed to set these tags, regardless of their other permissions."

Any additional context that might be helpful should be included as well.

**Comment by divyabhushan** [comment]
The changes are live in the doc. Hence, closing this issue.
@Pubs-MV
