### ISSUE TITLE
Prisma Cloud Compute/Scan reports doc page compliance ID 411 issue

### ISSUE THREAD

**Issue by panwsislam** [PaloAltoNetworks/prisma-cloud-docs#787]
## Documentation link

(https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/vulnerability_management/scan_reports)

## Describe the problem

The table at the bottom of the doc page describing compliance ID and package types has an incorrect package type for ID 411.
ID 411 is listed as package type: ie. MySgl

## Suggested fix

It should be 
ID 411 Package type: Binary

https://panw-gcs.slack.com/archives/CL11MD99Q/p1639056055306300?thread_ts=1639049475.304900&cid=CL11MD99Q

**Comment by Pubs-MV** [comment]
Can you please look into this @divyabhushan

**Comment by Pubs-MV** [comment]
addressed in 22.12 and PCEE
