### ISSUE TITLE
Twistcli sandbox scan doc missing requirement

### ISSUE THREAD

**Issue by panwsislam** [PaloAltoNetworks/prisma-cloud-docs#881]
## Documentation link
(https://docs.paloaltonetworks.com/prisma/prisma-cloud/22-06/prisma-cloud-compute-edition-admin/runtime_defense/image_analysis_sandbox)

## Describe the problem

This page is missing a requirement to run the "twistcli sandbox" command. 

## Suggested fix

Please add that "sudo" or root privilege is required to run a "twistcli sandbox" scan. 
This was also discussed and confirmed by PM: https://panw-gcs.slack.com/archives/CL11MD99Q/p1630487899209700

**Comment by Pubs-MV** [comment]
@divyabhushan please review the 22-12 docs and make the changes required.
