### ISSUE TITLE
Azure Ingestion API

### ISSUE THREAD

**Issue by asjonathanb** [PaloAltoNetworks/prisma-cloud-docs#894]
## Documentation link

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/connect-your-cloud-platform-to-prisma-cloud/onboard-your-azure-account/microsoft-azure-apis-ingested-by-prisma-cloud

## Describe the problem

At least one API is missing: 'azure-active-directory-app-registration' 
## Suggested fix

Please add it to the documentation.

**Comment by asjonathanb** [comment]
We figured out, that the following APIs are missing:
- azure-active-directory-app-registration (listed already above)
- azure-active-directory-custom-domain
- azure-active-directory-enterprise-applications
- azure-active-directory-group
- azure-active-directory-named-location
- azure-active-directory-service-principal-app
- azure-active-directory-user

thx and regards
Jonathan

**Comment by Pubs-MV** [comment]
please review @jenjoe22

**Comment by jenjoe22** [comment]
Thanks for bringing this to our attention Jonathon. I have updated the Gsheet that the docs pulls the Azure Ingested APIs from.

**Comment by jenjoe22** [comment]
Updated Gsheet with permissions that Jonathon raised. I also confirmed these can be added by checking with Surjit Singh.
